### ISSUE TITLE
Deprecated loop keyword argument

### ISSUE THREAD

**Issue by TibLiRoN** [jockesyk/homeassistant-yale-doorman-via-smarthub#22]
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: 13. desember 2021, 17:29:33 (1 occurrences)
Last logged: 13. desember 2021, 17:29:33

Detected integration that called async_timeout.timeout with loop keyword argument. The loop keyword argument is deprecated and calls will fail after Home Assistant 2022.2. Please report issue to the custom component author for yale_doorman_via_smarthub using this method at custom_components/yale_doorman_via_smarthub/api.py, line 116: async with async_timeout.timeout(TIMEOUT, loop=asyncio.get_event_loop()):

**Comment by bananflugan** [comment]
Will this be looked at?

**Comment by jockesyk** [comment]
This is hopefully fixed in version 0.0.6
