### ISSUE TITLE
Need help for install 

### ISSUE THREAD

**Issue by MatTurac** [jockesyk/homeassistant-yale-doorman-via-smarthub#23]
Hi all

Is there any one who could help with at step by step guide on how to install this?

So far I have installed the integrations in “HACS”….
What is the next step 😬🤔

**Comment by E-K-I** [comment]
Go to Integrations -> click on add Add Integration ->search for Yale Doorman via Smarthub -> install and configure

**Comment by MatTurac** [comment]
> Go to Integrations -> click on add Add Integration ->search for Yale Doorman via Smarthub -> install and configure

Thank you very much 🙏😃

**Comment by Marmoulak** [comment]
Hi, when I search in HACS for Yale Doorman via Smarthub can not find it. what I do wrong? 
![image](https://user-images.githubusercontent.com/44494190/148542793-5cd56586-47c5-43ad-8490-d0520c164aea.png)

**Comment by E-K-I** [comment]
Go to the Integrations page in HACS and select the three dots in the top right corner. Select Custom repositories

**Comment by Marmoulak** [comment]
Thanks E-K-I, But what is name of Custom Repositories? I can not find Smarthub or Yale Doorman.

**Comment by Marmoulak** [comment]
How can I use it now? I have installed "Yale Smart Living" from integration too.

**Comment by E-K-I** [comment]
If you have installed it you have a lock in your entity list. https://www.home-assistant.io/integrations/lock/

**Comment by Marmoulak** [comment]
I works perfect. thanks. 
Can I see if it is secure locked? If I have this state I can use it to arm/dissarm my alarm.

**Comment by E-K-I** [comment]
Try it and find out
