### ISSUE TITLE
Warning message in HA log

### ISSUE THREAD

**Issue by E-K-I** [jockesyk/homeassistant-yale-doorman-via-smarthub#25]
This warning appears after each restart of Home Assistant:

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
First occurred: 03:03:06 (1 occurrences)
Last logged: 03:03:06

Entity lock.hoveddor (<class 'custom_components.yale_doorman_via_smarthub.lock.YaleDoormanViaSmarthubLock'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by jockesyk** [comment]
Fixed in version 0.0.7
