### ISSUE TITLE
Error connecting to Yale hub

### ISSUE THREAD

**Issue by andersovreseth** [jockesyk/homeassistant-yale-doorman-via-smarthub#32]
Hello all, I have had this setup running for a long time, but some months back it failed. Here is the only error message I see in the logs:

2023-01-02 08:34:10.213 ERROR (MainThread) [custom_components.yale_doorman_via_smarthub] Timeout error fetching information from https://mob.yalehomesystem.co.uk/yapi/api/minigw/unlock/ -

Can anyone help me out?

**Comment by andersovreseth** [comment]
Looks like this plugin is not being maintained anymore.

**Comment by MatTurac** [comment]
Hi Anders 

I use this plugin, and it still works fine. 

Do your, Yale home app still work?

**Comment by andersovreseth** [comment]
Thanks for your feedback, I have indeed done a change in DNS-servers from google-servers to the fiber companys own servers. Is there a procedure for how to get it back up running? I have of course restarted on many levels, both the HA docker instance as well as the whole server already.

**Comment by andersovreseth** [comment]
I have tried the following; removed the integration (delete) and add it again. Input configuration details and add new card based on the newly added entity. This whole process did not bring any change.

Do I need to remove the integration from HACS and re-add?

**Comment by jockesyk** [comment]
Try to find a tutorial for changing and testing network settings for your type of Home Assistant installation.

Maybe this can help:
https://community.home-assistant.io/t/how-to-change-dns-setting-in-hassio/194197
